- import_playbook: create-user-bin.yaml

- hosts: all
  tasks:

  - name: Get docker-compose latest version
    shell: "curl -Ls -o /dev/null -w %{url_effective} https://github.com/docker/compose/releases/latest | sed -e 's|.*/||'"
    args:
      warn: false
    register: version

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ version.stdout }}/docker-compose-Linux-x86_64
      dest: "{{ lookup('env', 'HOME') }}/bin/docker-compose-{{ version.stdout }}"
      mode: '744'

  - name: Create a symbolic link
    file:
      src: "{{ lookup('env', 'HOME') }}/bin/docker-compose-{{ version.stdout }}"
      dest: "{{ lookup('env', 'HOME') }}/bin/docker-compose"
      state: link
